---
micronaut:
    application:
        name: securityrule
    security:
      enabled: true
      endpoints:
        login:
          enabled: true
        oauth:
          enabled: true
      token:
        jwt:
          enabled: true
          signatures:
            secret:
              generator:
                secret: pleaseChangeThisSecretForANewOne

jackson:
    module-scan: false
---
hibernate:
  hbm2ddl:
    auto: update
#  cache:
#    queries: false
#    use_second_level_cache: true
#    use_query_cache: false
    # region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
dataSources:
  test:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  test1:
    url: jdbc:h2:mem:devDb1;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''